apiVersion: k8cc.io/v1alpha1
kind: DistccClient
metadata:
  name: master
  labels:
    build-tag: master
spec:
  leaseDuration: 1h
  selector:
    matchLabels:
      build-tag: master
  template:
    metadata:
      labels:
        build-tag: master
    spec:
      containers:
        - name: client
          image: btwiuse/distcc-client-ubuntu:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 22
          volumeMounts:
            - name: ssh
              mountPath: /home/dev/.ssh
              readOnly: true
              mode: 0755
