apiVersion: k8cc.io/v1alpha1
kind: DistccClientClaim
metadata:
  name: mike-master
  labels:
    build-tag: master
spec:
  distccClientName: master
  userName: mike
  secrets:
    - name: ssh
      volumeSource:
        secretName: mike-ssh-key
        defaultMode: 0755
