# explicit requires for codegen
required = ["k8s.io/code-generator/cmd/client-gen",
            "k8s.io/code-generator/cmd/defaulter-gen",
            "k8s.io/code-generator/cmd/lister-gen",
            "k8s.io/code-generator/cmd/informer-gen",
            "k8s.io/code-generator/cmd/deepcopy-gen",
]

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.9.3"

# goland/dep does not follow k8s.io/code-generator's Godeps.json and gengo's master
# version does not work with release-1.8 k8s.io/code-generator. So we have to
# override it.
[[override]]
  name = "k8s.io/gengo"
  revision = "b58fc7edb82e0c6ffc9b8aef61813c7261b785d4"
