# explicit requires for codegen
required = ["k8s.io/code-generator/cmd/client-gen",
            "k8s.io/code-generator/cmd/defaulter-gen",
            "k8s.io/code-generator/cmd/lister-gen",
            "k8s.io/code-generator/cmd/informer-gen",
            "k8s.io/code-generator/cmd/deepcopy-gen",
]

[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.8"

# goland/dep does not follow k8s.io/code-generator's Godeps.json and gengo's master
# version does not work with release-1.8 k8s.io/code-generator. So we have to
# override it.
[[override]]
  name = "k8s.io/gengo"
  revision = "9e661e9308f078838e266cca1c673922088c0ea4"
