apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8cc-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8cc-controller
subjects:
- kind: ServiceAccount
  name: k8cc-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8cc-controller
rules:
- apiGroups: [""]
  resources:
  - services
  verbs: ["create", "get", "list"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["create", "get", "list"]
- apiGroups:
  - k8cc.io
  resources:
  - distccs
  - distccclients
  verbs: ["get", "list", "update"]
- apiGroups:
  - k8cc.io
  resources:
  - distccclaims
  - distccclientclaims
  verbs: ["delete", "get", "list", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8cc-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8cc-controller
  labels:
    app: k8cc
    tier: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8cc
      tier: controller
  template:
    metadata:
      labels:
        app: k8cc
        tier: controller
    spec:
      containers:
      - name: k8cc-controller
        image: mbrt/k8cc-controller:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccountName: k8cc-controller
